# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timetrace_view.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TimetraceView(object):
    def setupUi(self, TimetraceView):
        TimetraceView.setObjectName(_fromUtf8("TimetraceView"))
        TimetraceView.resize(950, 755)
        self.centralwidget = QtGui.QWidget(TimetraceView)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.plotSplitter = QtGui.QSplitter(self.centralwidget)
        self.plotSplitter.setOrientation(QtCore.Qt.Vertical)
        self.plotSplitter.setObjectName(_fromUtf8("plotSplitter"))
        self.drain_current_plot = QtGui.QGraphicsView(self.plotSplitter)
        self.drain_current_plot.setObjectName(_fromUtf8("drain_current_plot"))
        self.gate_current_plot = QtGui.QGraphicsView(self.plotSplitter)
        self.gate_current_plot.setObjectName(_fromUtf8("gate_current_plot"))
        self.horizontalLayout.addWidget(self.plotSplitter)
        TimetraceView.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(TimetraceView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        TimetraceView.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(TimetraceView)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        TimetraceView.setStatusBar(self.statusbar)
        self.voltagesDock = QtGui.QDockWidget(TimetraceView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voltagesDock.sizePolicy().hasHeightForWidth())
        self.voltagesDock.setSizePolicy(sizePolicy)
        self.voltagesDock.setMaximumSize(QtCore.QSize(300, 300))
        self.voltagesDock.setObjectName(_fromUtf8("voltagesDock"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.dsVoltageSet = QtGui.QDoubleSpinBox(self.groupBox)
        self.dsVoltageSet.setDecimals(3)
        self.dsVoltageSet.setSingleStep(0.001)
        self.dsVoltageSet.setObjectName(_fromUtf8("dsVoltageSet"))
        self.gridLayout_2.addWidget(self.dsVoltageSet, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.pulseDelay = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.pulseDelay.setObjectName(_fromUtf8("pulseDelay"))
        self.gridLayout.addWidget(self.pulseDelay, 3, 1, 1, 2)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.pulsedVoltageCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.pulsedVoltageCheckBox.setObjectName(_fromUtf8("pulsedVoltageCheckBox"))
        self.gridLayout.addWidget(self.pulsedVoltageCheckBox, 1, 0, 1, 3)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.pulseWidth = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.pulseWidth.setObjectName(_fromUtf8("pulseWidth"))
        self.gridLayout.addWidget(self.pulseWidth, 2, 1, 1, 2)
        self.gsVoltageSet = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.gsVoltageSet.setDecimals(3)
        self.gsVoltageSet.setSingleStep(0.001)
        self.gsVoltageSet.setObjectName(_fromUtf8("gsVoltageSet"))
        self.gridLayout.addWidget(self.gsVoltageSet, 0, 1, 1, 2)
        self.pulseCount = QtGui.QSpinBox(self.groupBox_2)
        self.pulseCount.setObjectName(_fromUtf8("pulseCount"))
        self.gridLayout.addWidget(self.pulseCount, 4, 1, 1, 2)
        self.pulsButton = QtGui.QPushButton(self.groupBox_2)
        self.pulsButton.setObjectName(_fromUtf8("pulsButton"))
        self.gridLayout.addWidget(self.pulsButton, 5, 0, 1, 3)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.voltagesDock.setWidget(self.dockWidgetContents_2)
        TimetraceView.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.voltagesDock)
        self.measuredDock = QtGui.QDockWidget(TimetraceView)
        self.measuredDock.setMaximumSize(QtCore.QSize(524287, 200))
        self.measuredDock.setObjectName(_fromUtf8("measuredDock"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_7 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 3)
        self.label_9 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.measureDrainV = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.measureDrainV.setObjectName(_fromUtf8("measureDrainV"))
        self.gridLayout_3.addWidget(self.measureDrainV, 0, 3, 1, 1)
        self.measuredDrainI = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.measuredDrainI.setObjectName(_fromUtf8("measuredDrainI"))
        self.gridLayout_3.addWidget(self.measuredDrainI, 1, 3, 1, 1)
        self.measureGateV = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.measureGateV.setObjectName(_fromUtf8("measureGateV"))
        self.gridLayout_3.addWidget(self.measureGateV, 2, 3, 1, 1)
        self.measuredGateI = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.measuredGateI.setObjectName(_fromUtf8("measuredGateI"))
        self.gridLayout_3.addWidget(self.measuredGateI, 3, 3, 1, 1)
        self.measuredDock.setWidget(self.dockWidgetContents_3)
        TimetraceView.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.measuredDock)
        self.settingsDock = QtGui.QDockWidget(TimetraceView)
        self.settingsDock.setMaximumSize(QtCore.QSize(524287, 100))
        self.settingsDock.setObjectName(_fromUtf8("settingsDock"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.dockWidgetContents_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_10 = QtGui.QLabel(self.dockWidgetContents_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 0, 0, 1, 1)
        self.gateIcutoff = QtGui.QDoubleSpinBox(self.dockWidgetContents_4)
        self.gateIcutoff.setObjectName(_fromUtf8("gateIcutoff"))
        self.gridLayout_4.addWidget(self.gateIcutoff, 0, 1, 1, 1)
        self.gateIcutoffUnits = QtGui.QComboBox(self.dockWidgetContents_4)
        self.gateIcutoffUnits.setObjectName(_fromUtf8("gateIcutoffUnits"))
        self.gateIcutoffUnits.addItem(_fromUtf8(""))
        self.gateIcutoffUnits.addItem(_fromUtf8(""))
        self.gateIcutoffUnits.addItem(_fromUtf8(""))
        self.gateIcutoffUnits.addItem(_fromUtf8(""))
        self.gateIcutoffUnits.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.gateIcutoffUnits, 0, 2, 1, 1)
        self.settingsDock.setWidget(self.dockWidgetContents_4)
        TimetraceView.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.settingsDock)
        self.controlDock = QtGui.QDockWidget(TimetraceView)
        self.controlDock.setMaximumSize(QtCore.QSize(524287, 200))
        self.controlDock.setObjectName(_fromUtf8("controlDock"))
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName(_fromUtf8("dockWidgetContents_6"))
        self.gridLayout_5 = QtGui.QGridLayout(self.dockWidgetContents_6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.StopButton = QtGui.QPushButton(self.dockWidgetContents_6)
        self.StopButton.setObjectName(_fromUtf8("StopButton"))
        self.gridLayout_5.addWidget(self.StopButton, 7, 1, 1, 1)
        self.StartButton = QtGui.QPushButton(self.dockWidgetContents_6)
        self.StartButton.setObjectName(_fromUtf8("StartButton"))
        self.gridLayout_5.addWidget(self.StartButton, 7, 0, 1, 1)
        self.experiment_name = QtGui.QLineEdit(self.dockWidgetContents_6)
        self.experiment_name.setInputMask(_fromUtf8(""))
        self.experiment_name.setDragEnabled(False)
        self.experiment_name.setObjectName(_fromUtf8("experiment_name"))
        self.gridLayout_5.addWidget(self.experiment_name, 2, 0, 1, 2)
        self.label_11 = QtGui.QLabel(self.dockWidgetContents_6)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 1, 0, 1, 2)
        self.controlDock.setWidget(self.dockWidgetContents_6)
        TimetraceView.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.controlDock)
        self.actionWorkinFolder = QtGui.QAction(TimetraceView)
        self.actionWorkinFolder.setObjectName(_fromUtf8("actionWorkinFolder"))
        self.actionExit = QtGui.QAction(TimetraceView)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionWorkinFolder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(TimetraceView)
        QtCore.QMetaObject.connectSlotsByName(TimetraceView)

    def retranslateUi(self, TimetraceView):
        TimetraceView.setWindowTitle(_translate("TimetraceView", "TMM (Timetrace Measurement Module)", None))
        self.menuFile.setTitle(_translate("TimetraceView", "File", None))
        self.voltagesDock.setWindowTitle(_translate("TimetraceView", "Voltages", None))
        self.groupBox.setTitle(_translate("TimetraceView", "Drain-Source Voltage", None))
        self.label.setText(_translate("TimetraceView", "DS_Voltage", None))
        self.groupBox_2.setTitle(_translate("TimetraceView", "Gate Voltage", None))
        self.label_3.setText(_translate("TimetraceView", "Pulse width", None))
        self.label_4.setText(_translate("TimetraceView", "Pulse delay", None))
        self.label_5.setText(_translate("TimetraceView", "Pulse count", None))
        self.pulsedVoltageCheckBox.setText(_translate("TimetraceView", "Pulsed", None))
        self.label_2.setText(_translate("TimetraceView", "GS_Voltage", None))
        self.pulsButton.setText(_translate("TimetraceView", "Pulse", None))
        self.measuredDock.setWindowTitle(_translate("TimetraceView", "Measured", None))
        self.label_7.setText(_translate("TimetraceView", "Drain I", None))
        self.label_6.setText(_translate("TimetraceView", "Drain V", None))
        self.label_9.setText(_translate("TimetraceView", "Gate I", None))
        self.label_8.setText(_translate("TimetraceView", "Gate V", None))
        self.settingsDock.setWindowTitle(_translate("TimetraceView", "Settings", None))
        self.label_10.setText(_translate("TimetraceView", "Gate Current Cutoff", None))
        self.gateIcutoffUnits.setItemText(0, _translate("TimetraceView", "A", None))
        self.gateIcutoffUnits.setItemText(1, _translate("TimetraceView", "mA", None))
        self.gateIcutoffUnits.setItemText(2, _translate("TimetraceView", "uA", None))
        self.gateIcutoffUnits.setItemText(3, _translate("TimetraceView", "nA", None))
        self.gateIcutoffUnits.setItemText(4, _translate("TimetraceView", "pA", None))
        self.controlDock.setWindowTitle(_translate("TimetraceView", "Controls", None))
        self.StopButton.setText(_translate("TimetraceView", "Stop", None))
        self.StartButton.setText(_translate("TimetraceView", "Start", None))
        self.label_11.setText(_translate("TimetraceView", "Experimant name", None))
        self.actionWorkinFolder.setText(_translate("TimetraceView", "WorkinFolder", None))
        self.actionExit.setText(_translate("TimetraceView", "Exit", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TimetraceView = QtGui.QMainWindow()
    ui = Ui_TimetraceView()
    ui.setupUi(TimetraceView)
    TimetraceView.show()
    sys.exit(app.exec_())

