# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_IV_Measurement_v3.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(975, 864)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.ui_plot = GraphicsLayoutWidget(self.centralwidget)
        self.ui_plot.setObjectName(_fromUtf8("ui_plot"))
        self.gridLayout_3.addWidget(self.ui_plot, 0, 0, 1, 1)
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_8.addWidget(self.label_7, 0, 0, 1, 1)
        self.ui_measurement_type = QtGui.QComboBox(self.frame)
        self.ui_measurement_type.setObjectName(_fromUtf8("ui_measurement_type"))
        self.gridLayout_8.addWidget(self.ui_measurement_type, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.ui_ds_start = QtGui.QLineEdit(self.groupBox)
        self.ui_ds_start.setObjectName(_fromUtf8("ui_ds_start"))
        self.gridLayout.addWidget(self.ui_ds_start, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.ui_ds_stop = QtGui.QLineEdit(self.groupBox)
        self.ui_ds_stop.setObjectName(_fromUtf8("ui_ds_stop"))
        self.gridLayout.addWidget(self.ui_ds_stop, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.ui_ds_points = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_ds_points.sizePolicy().hasHeightForWidth())
        self.ui_ds_points.setSizePolicy(sizePolicy)
        self.ui_ds_points.setMinimum(1)
        self.ui_ds_points.setMaximum(501)
        self.ui_ds_points.setObjectName(_fromUtf8("ui_ds_points"))
        self.gridLayout.addWidget(self.ui_ds_points, 2, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.frame)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.ui_gs_start = QtGui.QLineEdit(self.groupBox_3)
        self.ui_gs_start.setObjectName(_fromUtf8("ui_gs_start"))
        self.gridLayout_2.addWidget(self.ui_gs_start, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.ui_gs_stop = QtGui.QLineEdit(self.groupBox_3)
        self.ui_gs_stop.setObjectName(_fromUtf8("ui_gs_stop"))
        self.gridLayout_2.addWidget(self.ui_gs_stop, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.ui_gs_points = QtGui.QSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_gs_points.sizePolicy().hasHeightForWidth())
        self.ui_gs_points.setSizePolicy(sizePolicy)
        self.ui_gs_points.setMinimum(1)
        self.ui_gs_points.setMaximum(501)
        self.ui_gs_points.setObjectName(_fromUtf8("ui_gs_points"))
        self.gridLayout_2.addWidget(self.ui_gs_points, 2, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_3, 3, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.ui_ds_resource = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_ds_resource.sizePolicy().hasHeightForWidth())
        self.ui_ds_resource.setSizePolicy(sizePolicy)
        self.ui_ds_resource.setObjectName(_fromUtf8("ui_ds_resource"))
        self.gridLayout_5.addWidget(self.ui_ds_resource, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 1, 0, 1, 1)
        self.ui_gs_resource = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_gs_resource.sizePolicy().hasHeightForWidth())
        self.ui_gs_resource.setSizePolicy(sizePolicy)
        self.ui_gs_resource.setObjectName(_fromUtf8("ui_gs_resource"))
        self.gridLayout_5.addWidget(self.ui_gs_resource, 1, 1, 1, 1)
        self.ui_hardware_sweep = QtGui.QCheckBox(self.groupBox_4)
        self.ui_hardware_sweep.setChecked(True)
        self.ui_hardware_sweep.setObjectName(_fromUtf8("ui_hardware_sweep"))
        self.gridLayout_5.addWidget(self.ui_hardware_sweep, 2, 0, 1, 2)
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 3, 0, 1, 1)
        self.ui_integration_time = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_integration_time.sizePolicy().hasHeightForWidth())
        self.ui_integration_time.setSizePolicy(sizePolicy)
        self.ui_integration_time.setObjectName(_fromUtf8("ui_integration_time"))
        self.gridLayout_5.addWidget(self.ui_integration_time, 3, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 4, 0, 1, 1)
        self.ui_current_compliance = QtGui.QLineEdit(self.groupBox_4)
        self.ui_current_compliance.setObjectName(_fromUtf8("ui_current_compliance"))
        self.gridLayout_5.addWidget(self.ui_current_compliance, 4, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 5, 0, 1, 1)
        self.ui_set_meas_delay = QtGui.QLineEdit(self.groupBox_4)
        self.ui_set_meas_delay.setObjectName(_fromUtf8("ui_set_meas_delay"))
        self.gridLayout_5.addWidget(self.ui_set_meas_delay, 5, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_5.addWidget(self.label_16, 6, 0, 1, 1)
        self.ui_averaging_count = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_averaging_count.sizePolicy().hasHeightForWidth())
        self.ui_averaging_count.setSizePolicy(sizePolicy)
        self.ui_averaging_count.setObjectName(_fromUtf8("ui_averaging_count"))
        self.gridLayout_5.addWidget(self.ui_averaging_count, 6, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_4, 4, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.ui_use_advanced_dialog = QtGui.QCheckBox(self.groupBox_2)
        self.ui_use_advanced_dialog.setObjectName(_fromUtf8("ui_use_advanced_dialog"))
        self.gridLayout_7.addWidget(self.ui_use_advanced_dialog, 0, 0, 1, 4)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_7.addWidget(self.label_12, 1, 0, 1, 1)
        self.ui_experimentName = QtGui.QLineEdit(self.groupBox_2)
        self.ui_experimentName.setObjectName(_fromUtf8("ui_experimentName"))
        self.gridLayout_7.addWidget(self.ui_experimentName, 1, 1, 1, 3)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_7.addWidget(self.label_13, 3, 0, 1, 1)
        self.ui_measurementName = QtGui.QLineEdit(self.groupBox_2)
        self.ui_measurementName.setMaxLength(32767)
        self.ui_measurementName.setObjectName(_fromUtf8("ui_measurementName"))
        self.gridLayout_7.addWidget(self.ui_measurementName, 3, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 3, 2, 1, 1)
        self.ui_measurementCount = QtGui.QSpinBox(self.groupBox_2)
        self.ui_measurementCount.setMaximum(99999)
        self.ui_measurementCount.setObjectName(_fromUtf8("ui_measurementCount"))
        self.gridLayout_7.addWidget(self.ui_measurementCount, 3, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_7.addWidget(self.label_14, 4, 0, 1, 1)
        self.folderBrowseButton = QtGui.QPushButton(self.groupBox_2)
        self.folderBrowseButton.setObjectName(_fromUtf8("folderBrowseButton"))
        self.gridLayout_7.addWidget(self.folderBrowseButton, 4, 1, 1, 3)
        self.ui_advanced_dialog_widget = QtGui.QWidget(self.groupBox_2)
        self.ui_advanced_dialog_widget.setObjectName(_fromUtf8("ui_advanced_dialog_widget"))
        self.ui_advanced_dialog_layout = QtGui.QGridLayout(self.ui_advanced_dialog_widget)
        self.ui_advanced_dialog_layout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.ui_advanced_dialog_layout.setContentsMargins(1, 9, 1, 9)
        self.ui_advanced_dialog_layout.setHorizontalSpacing(11)
        self.ui_advanced_dialog_layout.setVerticalSpacing(9)
        self.ui_advanced_dialog_layout.setObjectName(_fromUtf8("ui_advanced_dialog_layout"))
        self.label_18 = QtGui.QLabel(self.ui_advanced_dialog_widget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.ui_advanced_dialog_layout.addWidget(self.label_18, 0, 0, 1, 1)
        self.ui_wafer_name = QtGui.QLineEdit(self.ui_advanced_dialog_widget)
        self.ui_wafer_name.setObjectName(_fromUtf8("ui_wafer_name"))
        self.ui_advanced_dialog_layout.addWidget(self.ui_wafer_name, 0, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.ui_advanced_dialog_widget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.ui_advanced_dialog_layout.addWidget(self.label_19, 1, 0, 1, 1)
        self.ui_chip_name = QtGui.QLineEdit(self.ui_advanced_dialog_widget)
        self.ui_chip_name.setObjectName(_fromUtf8("ui_chip_name"))
        self.ui_advanced_dialog_layout.addWidget(self.ui_chip_name, 1, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.ui_advanced_dialog_widget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.ui_advanced_dialog_layout.addWidget(self.label_20, 2, 0, 1, 1)
        self.ui_transistor_number = QtGui.QSpinBox(self.ui_advanced_dialog_widget)
        self.ui_transistor_number.setMinimum(1)
        self.ui_transistor_number.setMaximum(32)
        self.ui_transistor_number.setObjectName(_fromUtf8("ui_transistor_number"))
        self.ui_advanced_dialog_layout.addWidget(self.ui_transistor_number, 2, 1, 1, 1)
        self.gridLayout_7.addWidget(self.ui_advanced_dialog_widget, 2, 0, 1, 4)
        self.gridLayout_8.addWidget(self.groupBox_2, 5, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem, 6, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.startButton = QtGui.QPushButton(self.frame_2)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout.addWidget(self.startButton)
        self.stopButton = QtGui.QPushButton(self.frame_2)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout.addWidget(self.stopButton)
        self.gridLayout_8.addWidget(self.frame_2, 7, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 975, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_7.setText(_translate("MainWindow", "Characteristic Type", None))
        self.groupBox.setTitle(_translate("MainWindow", "Drain-Source Voltage", None))
        self.label.setText(_translate("MainWindow", "Start", None))
        self.label_2.setText(_translate("MainWindow", "Stop", None))
        self.label_3.setText(_translate("MainWindow", "Points", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Gate-Source Voltage", None))
        self.label_4.setText(_translate("MainWindow", "Start", None))
        self.label_5.setText(_translate("MainWindow", "Stop", None))
        self.label_6.setText(_translate("MainWindow", "Points", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Properties", None))
        self.label_8.setText(_translate("MainWindow", "DS Keithley", None))
        self.label_9.setText(_translate("MainWindow", "GS Keithley", None))
        self.ui_hardware_sweep.setText(_translate("MainWindow", "Hardware sweep", None))
        self.label_10.setText(_translate("MainWindow", "Integration time", None))
        self.label_11.setText(_translate("MainWindow", "Current compliance", None))
        self.label_15.setText(_translate("MainWindow", "Set-Measure delay", None))
        self.label_16.setText(_translate("MainWindow", "Averaging count", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Save Data", None))
        self.ui_use_advanced_dialog.setText(_translate("MainWindow", "Use transistor save dialog", None))
        self.label_12.setText(_translate("MainWindow", "Experiment", None))
        self.label_13.setText(_translate("MainWindow", "Measurement", None))
        self.label_17.setText(_translate("MainWindow", "#", None))
        self.label_14.setText(_translate("MainWindow", "Folder", None))
        self.folderBrowseButton.setText(_translate("MainWindow", "...", None))
        self.label_18.setText(_translate("MainWindow", "Wafer name", None))
        self.label_19.setText(_translate("MainWindow", "Chip name", None))
        self.label_20.setText(_translate("MainWindow", "Transistor", None))
        self.startButton.setText(_translate("MainWindow", "Start", None))
        self.stopButton.setText(_translate("MainWindow", "Stop", None))

from pyqtgraph import GraphicsLayoutWidget
